spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
default:
  filepath: "/home/daniil/default_links.txt"
  url: "https://pokeapi.co"