spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  jpa:
    properties:
      hibernate:
        dialect: whale.CustomClickhouseDialect
default:
  save-to-clickhouse: true
  filepath: "/home/daniil/default_links.txt"
  url: "https://pokeapi.co"
  redis:
    url: localhost
    port: 6379
  clickhouse:
    url:
    port: